// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type DoneFilter struct {
	Done bool `json:"done"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User User   `json:"user"`
}

type UpdateTodo struct {
	ID   string `json:"id"`
	Done bool   `json:"done"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserFilter struct {
	ID string `json:"id"`
}

type UserNameFilter struct {
	Name *string `json:"name"`
}
